import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

final ThemeData darkTheme = ThemeData(
  brightness: Brightness.dark,
  textTheme: GoogleFonts.onestTextTheme().apply(
    bodyColor: const Color(0xFFEEF1F5),
    displayColor: const Color(0xFFEEF1F5),
    decorationColor: const Color(0xFFEEF1F5),
  ),
  scaffoldBackgroundColor: const Color(0xFF150d24),
  cardColor: const Color(0xFF21192F),
  canvasColor: const Color(0xFF21192F),
  splashColor: Colors.transparent,
  highlightColor: Colors.transparent,
  primaryColor: const Color(0xFFAEE67F),
  primaryColorLight: const Color(0xFFC3E7A5),
  colorScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFAEE67F),
    onPrimary: Color(0xFF150D24),
    primaryContainer: Color(0xFFAEE67F),
    onPrimaryContainer: Color(0xFF150D24),
    primaryFixed: Color(0xFF9CD96C),
    primaryFixedDim: Color(0xFFBDECB6),
    onPrimaryFixed: Color(0xFF203D29),
    onPrimaryFixedVariant: Color(0xFF4A7745),
    secondary: Color(0xFF6447AF),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFF6447AF),
    onSecondaryContainer: Color(0xFFFFFFFF),
    secondaryFixed: Color(0xFF7C5BC8),
    secondaryFixedDim: Color(0xFF927AD1),
    onSecondaryFixed: Color(0xFFEDE7F6),
    onSecondaryFixedVariant: Color(0xFFD1C4E9),
    tertiary: Color(0xFFEA852C),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFEA852C),
    onTertiaryContainer: Color(0xFFFFFFFF),
    tertiaryFixed: Color(0xFFF0A564),
    tertiaryFixedDim: Color(0xFFF6BD8F),
    onTertiaryFixed: Color(0xFF603D30),
    onTertiaryFixedVariant: Color(0xFF8C6A55),
    error: Color(0xFFB71849),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFD9DD),
    onErrorContainer: Color(0xFFB71849),
    surface: Color(0xFF150d24),
    onSurface: Color(0xFFEEF1F5),
    surfaceDim: Color(0xFF231C1C),
    surfaceBright: Color(0xFF1D1925),
    surfaceContainerLowest: Color(0xFF120A20),
    surfaceContainerLow: Color(0xFF1A1A1A),
    surfaceContainer: Color(0xFF21192f),
    surfaceContainerHigh: Color(0xFF251E32),
    surfaceContainerHighest: Color(0xFF2A2436),
    onSurfaceVariant: Color(0xFFEEF1F5),
    outline: Color(0xFF768190),
    outlineVariant: Color(0xFFBDBDBD),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF795548),
    inverseSurface: Color(0xFF303030),
    onInverseSurface: Color(0xFFF5F5F5),
    inversePrimary: Color(0xFF00C853),
    surfaceTint: Color(0xFFAEE67F),
  ),
);
