import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

final ThemeData lightTheme = ThemeData(
  brightness: Brightness.light,
  textTheme: GoogleFonts.onestTextTheme(),
  scaffoldBackgroundColor: const Color(0xFFF8F9FA),
  cardColor: const Color(0xFFFFFFFF),
  canvasColor: const Color(0xFFFFFFFF),
  splashColor: Colors.transparent,
  highlightColor: Colors.transparent,
  primaryColor: const Color(0xFF64DD17),
  primaryColorLight: const Color(0xFF81F97A),
  colorScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF64DD17),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFAEE67F),
    onPrimaryContainer: Color(0xFF1B5E20),
    primaryFixed: Color(0xFF64DD17),
    primaryFixedDim: Color(0xFF81F97A),
    onPrimaryFixed: Color(0xFF004D00),
    onPrimaryFixedVariant: Color(0xFF33691E),
    secondary: Color(0xFF7C4DFF),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFEDE7F6),
    onSecondaryContainer: Color(0xFF512DA8),
    secondaryFixed: Color(0xFF7C4DFF),
    secondaryFixedDim: Color(0xFFD1C4E9),
    onSecondaryFixed: Color(0xFF311B92),
    onSecondaryFixedVariant: Color(0xFFB39DDB),
    tertiary: Color(0xFFFF6D00),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFFD1A3),
    onTertiaryContainer: Color(0xFFBF360C),
    tertiaryFixed: Color(0xFFFF9100),
    tertiaryFixedDim: Color(0xFFFFAB40),
    onTertiaryFixed: Color(0xFF4E342E),
    onTertiaryFixedVariant: Color(0xFF795548),
    error: Color(0xFFD50000),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFD6D6),
    onErrorContainer: Color(0xFFD50000),
    surface: Color(0xFFFFFFFF),
    onSurface: Color(0xFF1E1E1E),
    surfaceDim: Color(0xFFECEFF1),
    surfaceBright: Color(0xFFFFFFFF),
    surfaceContainerLowest: Color(0xFFF5F5F5),
    surfaceContainerLow: Color(0xFFFAFAFA),
    surfaceContainer: Color(0xFFFFFFFF),
    surfaceContainerHigh: Color(0xFFF2F2F2),
    surfaceContainerHighest: Color(0xFFECEFF1),
    onSurfaceVariant: Color(0xFF424242),
    outline: Color(0xFFBDBDBD),
    outlineVariant: Color(0xFFE0E0E0),
    shadow: Color(0xFF000000),
    scrim: Color(0xFFEEEEEE),
    inverseSurface: Color(0xFF2C2C2C),
    onInverseSurface: Color(0xFFF5F5F5),
    inversePrimary: Color(0xFF00E676),
    surfaceTint: Color(0xFF64DD17),
  ),
);
